version: '3.8'

services:
  mariadb:
    container_name: sqwadz-dev
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - sqwadz-net
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - '3307:3306'

  redis:
    container_name: sqwadz-dev-redis
    image: redis
    restart: unless-stopped
    command: ['redis-server', '--requirepass', '${REDIS_PASSWORD}']
    networks:
      - sqwadz-net
    volumes:
      - redis-data:/data
    ports:
      - '6379:6379'

networks:
  sqwadz-net:
    name: SQWADZ-NET

volumes:
  mariadb-data:
  redis-data:
