version: '3'

services:
  app:
    container_name: sqwadz-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
    volumes:
      - app:/app
      - node_modules:/app/node_modules
    ports:
      - 3000:3000
    networks:
      - SQWADZ-NET
    restart: unless-stopped
    pull_policy: build
    domainname: beta.sqwadz.com

networks:
  SQWADZ-NET:
    external: true

volumes:
  app:
  node_modules:
