name: Build and Deploy
on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install pnpm
      run: npm install -g pnpm@9.6.0

    - name: Cache pnpm store
      uses: actions/cache@v4
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: pnpm install --frozen-lockfile --reporter=append-only --loglevel=debug

    - name: Node.js and pnpm info
      run: |
        node -v
        pnpm -v
        pnpm list --depth=0

    - name: Build
      run: pnpm run build

    - name: Generate Prisma client
      env:
        DATABASE_URL: ${{ github.ref == 'refs/heads/main' && secrets.DATABASE_URL || secrets.DATABASE_URL_DEV }}
      run: npx prisma migrate deploy

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ github.ref == 'refs/heads/main' && 'ipajudd/sqwadz:latest' || '' }}
          ${{ github.ref == 'refs/heads/dev' && 'ipajudd/sqwadz-dev:latest' || '' }}
